

# # version of the docker compose syntax 
# version: '3.9'
# # main block of the docker compose file
# services:
#   app:
#     build: .
#     args:
#       - DEV="true"
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app:/app
#     command: >
#       sh -c "python manage.py runserver 0.0.0.0:8000"

version: "3.9"

services:   
  app:
    build:
      context: .
      args:
       - DEV=true
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    